# -*- coding: utf-8 -*-
"""InternCircle_Task4_Personal_Expense_Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LEJpucvfr4lHtfCVRc8n13SazLLOqUaI
"""

# ==========================================
# TASK 4: PERSONAL EXPENSE TRACKER WITH CSV
# InternCircle
# ==========================================

import csv
import os

FILE_NAME = "expenses.csv"


# Create CSV file if it does not already exist
def create_file():
    if not os.path.exists(FILE_NAME):
        with open(FILE_NAME, "w", newline="", encoding="utf-8") as file:
            writer = csv.writer(file)
            writer.writerow(["Date", "Category", "Description", "Amount"])


# Add a new expense
def add_expense():
    print("\n========== ADD EXPENSE ==========")

    date = input("Enter date (DD-MM-YYYY): ")
    category = input("Enter category: ")
    description = input("Enter description: ")

    while True:
        try:
            amount = float(input("Enter amount: "))

            if amount <= 0:
                print("Amount must be greater than 0.")
            else:
                break

        except ValueError:
            print("Invalid amount! Please enter a number.")

    with open(FILE_NAME, "a", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerow([date, category, description, amount])

    print("\nExpense added successfully!")


# View all expenses
def view_expenses():
    print("\n========== ALL EXPENSES ==========")

    with open(FILE_NAME, "r", newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)

        expenses = list(reader)

        if not expenses:
            print("No expenses recorded yet.")
            return

        print("\nDate\t\tCategory\tDescription\tAmount")
        print("-" * 60)

        for expense in expenses:
            print(
                f"{expense['Date']}\t"
                f"{expense['Category']}\t"
                f"{expense['Description']}\t"
                f"₹{float(expense['Amount']):.2f}"
            )


# Filter expenses by category
def filter_expenses():
    print("\n========== FILTER EXPENSES ==========")

    category = input("Enter category to filter: ").lower()

    with open(FILE_NAME, "r", newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)

        found = False
        total = 0

        print("\nDate\t\tCategory\tDescription\tAmount")
        print("-" * 60)

        for expense in reader:
            if expense["Category"].lower() == category:
                print(
                    f"{expense['Date']}\t"
                    f"{expense['Category']}\t"
                    f"{expense['Description']}\t"
                    f"₹{float(expense['Amount']):.2f}"
                )

                total += float(expense["Amount"])
                found = True

        if found:
            print("\nTotal for", category, ":", f"₹{total:.2f}")
        else:
            print("\nNo expenses found for this category.")


# Category summary
def category_summary():
    print("\n========== CATEGORY SUMMARY ==========")

    summary = {}

    with open(FILE_NAME, "r", newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)

        for expense in reader:
            category = expense["Category"]
            amount = float(expense["Amount"])

            if category in summary:
                summary[category] += amount
            else:
                summary[category] = amount

    if not summary:
        print("No expenses recorded yet.")
        return

    print("\nCategory\tTotal Amount")
    print("-" * 35)

    for category, total in summary.items():
        print(f"{category}\t\t₹{total:.2f}")


# Main menu
def main():
    create_file()

    while True:
        print("\n====================================")
        print("       PERSONAL EXPENSE TRACKER")
        print("====================================")
        print("1. Add Expense")
        print("2. View All Expenses")
        print("3. Filter by Category")
        print("4. Category Summary")
        print("5. Exit")
        print("====================================")

        choice = input("Enter your choice (1-5): ")

        if choice == "1":
            add_expense()

        elif choice == "2":
            view_expenses()

        elif choice == "3":
            filter_expenses()

        elif choice == "4":
            category_summary()

        elif choice == "5":
            print("\nThank you for using Personal Expense Tracker!")
            break

        else:
            print("\nInvalid choice! Please enter a number from 1 to 5.")


# Run the program
main()